//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public long USU_CODIGO { get; set; }
        public string USU_NOMBRE { get; set; }
        public string USU_APELLIDO { get; set; }
        public string USU_CEDULA { get; set; }
        public string USU_DIRECCION { get; set; }
        public string USU_TELEFONO { get; set; }
        public string USU_EMAIL { get; set; }
        public string USU_USUARIO { get; set; }
        public string USU_PASSWORD { get; set; }
        public bool USU_ISADMIN { get; set; }
    }
}
